name = "Gaming Grudge"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a57a5349dfe397de0621eb28e96a951c57a123cc131e74fd40259031169b00ed"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
