name = "Gaming Grudge"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8785475e65f6b52312e26bc29a168cf78ee53075d65a230f702714e3cd13f88"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
