name = "Gaming Grudge"
author = "Nayruden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52174dd100b876bd058cba4f2fff04e271feb1b2abe77d0f27abf0dcc4dbe229"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
